name: Dino Animation

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Criar pasta de saída
        run: mkdir -p output

      - name: Gerar animação do Dino
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="200">' > output/dino.svg
          echo '  <rect width="100%" height="100%" fill="white"/>' >> output/dino.svg
          echo '  <line x1="0" y1="150" x2="800" y2="150" stroke="#555" stroke-width="2" stroke-dasharray="6,6"/>' >> output/dino.svg
          echo '  <g fill="none" stroke="#bbb" stroke-width="2">' >> output/dino.svg
          echo '    <path d="M60 50 q10 -10 20 0 q10 -10 20 0 q10 10 20 0">' >> output/dino.svg
          echo '      <animateTransform attributeName="transform" type="translate" from="0 0" to="-900 0" dur="40s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '    </path>' >> output/dino.svg
          echo '    <path d="M200 30 q15 -10 30 0 q15 -10 30 0 q15 10 30 0">' >> output/dino.svg
          echo '      <animateTransform attributeName="transform" type="translate" from="0 0" to="-900 0" dur="60s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '    </path>' >> output/dino.svg
          echo '  </g>' >> output/dino.svg
          # Dino frame 1
          echo '  <g id="dino1">' >> output/dino.svg
          echo '    <rect x="50" y="100" width="40" height="40" fill="black"/>' >> output/dino.svg
          echo '    <rect x="85" y="110" width="20" height="20" fill="black"/>' >> output/dino.svg
          echo '    <rect x="100" y="115" width="4" height="4" fill="white"/>' >> output/dino.svg
          echo '    <rect x="40" y="110" width="10" height="10" fill="black"/>' >> output/dino.svg
          echo '    <rect x="55" y="140" width="10" height="10" fill="black"/>' >> output/dino.svg
          echo '    <rect x="75" y="145" width="10" height="5" fill="black"/>' >> output/dino.svg
          echo '  </g>' >> output/dino.svg
          # Dino frame 2
          echo '  <g id="dino2" visibility="hidden">' >> output/dino.svg
          echo '    <rect x="50" y="100" width="40" height="40" fill="black"/>' >> output/dino.svg
          echo '    <rect x="85" y="110" width="20" height="20" fill="black"/>' >> output/dino.svg
          echo '    <rect x="100" y="115" width="4" height="4" fill="white"/>' >> output/dino.svg
          echo '    <rect x="40" y="110" width="10" height="10" fill="black"/>' >> output/dino.svg
          echo '    <rect x="55" y="145" width="10" height="5" fill="black"/>' >> output/dino.svg
          echo '    <rect x="75" y="140" width="10" height="10" fill="black"/>' >> output/dino.svg
          echo '  </g>' >> output/dino.svg
          # Alternar frames
          echo '  <animate xlink:href="#dino1" attributeName="visibility" values="visible;hidden" dur="0.4s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '  <animate xlink:href="#dino2" attributeName="visibility" values="hidden;visible" dur="0.4s" repeatCount="indefinite"/>' >> output/dino.svg
          # Cactos
          echo '  <rect x="800" y="120" width="20" height="30" fill="black">' >> output/dino.svg
          echo '    <animate attributeName="x" from="800" to="-50" dur="4s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '  </rect>' >> output/dino.svg
          echo '  <rect x="1000" y="110" width="20" height="40" fill="black">' >> output/dino.svg
          echo '    <animate attributeName="x" from="1000" to="-50" dur="6s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '  </rect>' >> output/dino.svg
          echo '  <g fill="black">' >> output/dino.svg
          echo '    <rect x="1200" y="100" width="20" height="50"/>' >> output/dino.svg
          echo '    <rect x="1225" y="120" width="20" height="30"/>' >> output/dino.svg
          echo '    <animateTransform attributeName="transform" type="translate" from="0 0" to="-1400 0" dur="8s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '  </g>' >> output/dino.svg
          echo '</svg>' >> output/dino.svg

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "update dino animation"
          add: "output/dino.svg"
