name: Dino Animation

on:
  schedule:
    - cron: "0 */12 * * *" # atualiza a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Dino Animation
        run: |
          mkdir -p output
          cat > output/dino.svg <<'EOF'
          <svg xmlns="http://www.w3.org/2000/svg" width="800" height="200">
            <rect width="100%" height="100%" fill="white"/>

            <!-- chão -->
            <rect x="0" y="150" width="100%" height="5" fill="#444"/>

            <!-- dino -->
            <rect id="dino" x="50" y="110" width="40" height="40" fill="black">
              <animateTransform attributeName="transform" type="translate"
                values="0,0; 0,-40; 0,0" dur="1s" repeatCount="indefinite"/>
            </rect>

            <!-- olho -->
            <circle cx="80" cy="120" r="3" fill="white"/>

            <!-- cactus -->
            <rect x="800" y="100" width="20" height="50" fill="green">
              <animate attributeName="x" from="800" to="-50" dur="3s" repeatCount="indefinite"/>
            </rect>
          </svg>
          EOF

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "update dino animation"
          add: "output/dino.svg"
