name: Dino Animation

on:
  schedule:
    - cron: "0 */12 * * *" # roda a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Criar pasta de saída
        run: mkdir -p output

      - name: Gerar animação do Dino
        run: |
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="200">' > output/dino.svg
          echo '  <rect width="100%" height="100%" fill="white"/>' >> output/dino.svg
          echo '  <line x1="0" y1="150" x2="800" y2="150" stroke="#555" stroke-width="2" stroke-dasharray="6,6"/>' >> output/dino.svg
          echo '  <g fill="none" stroke="#bbb" stroke-width="2">' >> output/dino.svg
          echo '    <path d="M60 50 q10 -10 20 0 q10 -10 20 0 q10 10 20 0">' >> output/dino.svg
          echo '      <animateTransform attributeName="transform" type="translate" from="0 0" to="-900 0" dur="40s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '    </path>' >> output/dino.svg
          echo '    <path d="M200 30 q15 -10 30 0 q15 -10 30 0 q15 10 30 0">' >> output/dino.svg
          echo '      <animateTransform attributeName="transform" type="translate" from="0 0" to="-900 0" dur="60s" repeatCount="indefinite"/>' >> output/dino.svg
          echo '    </path>' >> output/dino.svg
          echo '  </g>' >> output/dino.svg
          # (continua com os demais elementos do SVG, usando echo >> output/dino.svg)

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "update dino animation"
          add: "output/dino.svg"
