name: Generate Dino Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dino Graph
        run: npm install dino-contribution-graph

      - name: Generate light theme
        run: |
          npx dino-contribution-graph \
            --platform github \
            --username Joaodevtech \
            --output output/dino-graph.svg

      - name: Generate dark theme
        run: |
          npx dino-contribution-graph \
            --platform github \
            --username Joaodevtech \
            --theme github-dark \
            --output output/dino-graph-dark.svg

      - name: Push output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin output || git checkout -b output
          git checkout -B output
          git add output/*.svg
          git commit -m "Update Dino Graph" || echo "No changes to commit"
          git push origin output --force
